var res = {
    MainScene_json : "images/maings/title_20481536.jpg",
    MapBG : "images/map/Friendly_Map.jpg",
    helvetica_fnt : "fonts/helvetica.fnt",
    helveticastoke_fnt : "fonts/helveticastoke.fnt",
    mdefensefont2_fnt : "fonts/mdefensefont2.fnt",
    mdefensefont_fnt : "fonts/mdefensefont.fnt",
    titlefont_fnt : "fonts/titlefont.fnt",
    whitefont1_fnt : "fonts/whitefont1.fnt",
    map1 : "images/maps/map1.jpg",
    map2 : "images/maps/map2.jpg",
    map3 : "images/maps/map3.jpg",
    itemshop_bg : "images/itemshop/1136.png",
    itemshop_item : "images/laboratory/ui_panel1.png",
    lab_bg : "images/laboratory/1136.png",

    atlas00: "images/map/choose.plist",
	atlas00_1: "images/gamescene.plist",
    atlas01: "images/effects/electro.plist",
    atlas02: "images/effects/lighting.plist",
    atlas03: "images/effects/splash.plist",
    atlas04: "images/effects/fire2.plist",
    atlas05: "images/effects/healing.blue.plist",
    atlas06: "images/effects/healing.red.plist",
    atlas07: "images/maps/animations/animations.plist",
    atlas08: "images/maps/animations/animations2.plist",
    atlas09: "images/gamescene/buttoln_skills.plist",
    atlas10: "images/bonusitems/dynamit.plist",
    atlas11: "images/bonusitems/spacestrike.plist",
    atlas12: "images/bonusitems/bombice.plist",
    atlas13: "images/towers/firegun/fire.plist",
    atlas14: "images/hero/hero_mine.plist",
    atlas15: "images/hero/hero_other.plist",
    atlas16: "images/towers/desant.fire.plist",
    atlas17: "images/towers/desant.left.plist",
    atlas18: "images/towers/desant.down.plist",
    atlas19: "images/towers/desant.up.plist",
    atlas20: "images/towers/desant.die.plist",
    atlas21: "images/towers/desant.nothing1.plist",
    atlas22: "images/towers/desant.nothing2.plist",
    atlas23: "images/towers/airbomb.plist",
    atlas24: "images/creeps/death.plist",
    atlas25: "",
    atlas26: "images/towers/firegun/1.1.plist",
    atlas27: "images/towers/firegun/1.2.plist",
    atlas28: "images/towers/firegun/1.3.plist",
    atlas29: "images/towers/firegun/1.4.plist",
    atlas30: "images/towers/firegun/2.1.plist",
    atlas31: "images/towers/firegun/2.2.plist",
    atlas32: "images/towers/firegun/2.3.plist",
    atlas33: "images/towers/firegun/2.4.plist",
    atlas34: "images/towers/firegun/3.1.plist",
    atlas35: "images/towers/firegun/3.2.plist",
    atlas36: "images/towers/firegun/3.3.plist",
    atlas37: "images/towers/firegun/3.4.plist",
    atlas38: "images/towers/firegun/4.1.plist",
    atlas39: "images/towers/firegun/4.2.plist",
    atlas40: "images/towers/firegun/4.3.plist",
    atlas41: "images/towers/firegun/4.4.plist",
    atlas42: "images/towers/firegun/5.1.plist",
    atlas43: "images/towers/firegun/5.2.plist",
    atlas44: "images/towers/firegun/5.3.plist",
    atlas45: "images/towers/firegun/5.4.plist",
    atlas46: "images/towers/minigun/1.plist",
    atlas47: "images/towers/minigun/2.plist",
    atlas48: "images/towers/minigun/3.plist",
    atlas49: "images/towers/minigun/4.plist",
    atlas50: "images/towers/minigun/5.plist",
    atlas51: "images/creeps/soldier.left.plist",
    atlas52: "images/creeps/soldier.down.plist",
    atlas53: "images/creeps/soldier.die.plist",
    atlas54: "images/creeps/soldier.up.plist",
    atlas55: "images/creeps/soldier.fire.plist",
    atlas56: "images/creeps/jeep.left.plist",
    atlas57: "images/creeps/jeep.down.plist",
    atlas58: "images/creeps/jeep.up.plist",
    atlas59: "images/creeps/jeep.fire.plist",
    atlas60: "images/hero/hero1.plist",
    atlas61: "images/hero/hero2.plist",
    atlas62: "images/hero/hero2_skils.plist",
    atlas63: "images/hero/hero3.plist",
    atlas64: "images/hero/hero3_bot.plist",
    atlas65: "images/hero/hero3_desant1.plist",
    atlas66: "images/hero/hero3_desant2.plist",
    atlas67: "images/hero/hero3_desant3.plist",
    atlas68: "images/towers/icegun/1.plist",
    atlas69: "images/towers/icegun/2.plist",
    atlas70: "images/towers/icegun/3.plist",
    atlas71: "images/towers/icegun/4.plist",
    atlas72: "images/towers/icegun/5.plist",
    atlas73: "images/towers/laser/laser.1.plist",
    atlas74: "images/towers/laser/laser.2.plist",
    atlas75: "images/towers/laser/laser.3.plist",
    atlas76: "images/towers/laser/laser.4.plist",
    atlas77: "images/towers/laser/laser.5.plist",
    atlas78: "images/towers/teslagun/1.plist",
    atlas79: "images/towers/teslagun/2.plist",
    atlas80: "images/towers/teslagun/3.plist",
    atlas81: "images/towers/teslagun/4.plist",
    atlas82: "images/towers/teslagun/5.plist",
    atlas83: "images/towers/roketgun/1.1.plist",
    atlas84: "images/towers/roketgun/1.2.plist",
    atlas85: "images/towers/roketgun/1.3.plist",
    atlas86: "images/towers/roketgun/1.4.plist",
    atlas87: "images/towers/roketgun/2.1.plist",
    atlas88: "images/towers/roketgun/2.2.plist",
    atlas89: "images/towers/roketgun/2.3.plist",
    atlas90: "images/towers/roketgun/2.4.plist",
    atlas91: "images/towers/roketgun/3.1.plist",
    atlas92: "images/towers/roketgun/3.2.plist",
    atlas93: "images/towers/roketgun/3.3.plist",
    atlas94: "images/towers/roketgun/3.4.plist",
    atlas95: "images/towers/roketgun/4.1.plist",
    atlas96: "images/towers/roketgun/4.2.plist",
    atlas97: "images/towers/roketgun/4.3.plist",
    atlas98: "images/towers/roketgun/4.4.plist",
    atlas99:  "images/towers/roketgun/5.1.plist",
    atlas100: "images/towers/roketgun/5.2.plist",
    atlas101: "images/towers/roketgun/5.3.plist",
    atlas102: "images/towers/roketgun/5.4.plist",
    atlas103: "images/creeps/soldier2.left.plist",
    atlas104: "images/creeps/soldier2.down.plist",
    atlas105: "images/creeps/soldier2.die.plist",
    atlas106: "images/creeps/soldier2.up.plist",
    atlas107: "images/creeps/soldier2.fire.plist",
    atlas108: "images/creeps/tank.left.plist",
    atlas109: "images/creeps/tank.down.plist",
    atlas110: "images/creeps/tank.up.plist",
    atlas111: "images/creeps/tank.fire.plist",
    atlas112: "images/creeps/medic.left.plist",
    atlas113: "images/creeps/medic.down.plist",
    atlas114: "images/creeps/medic.die.plist",
    atlas115: "images/creeps/medic.up.plist",
    atlas116: "images/creeps/medic.fire.plist",
    atlas117: "images/creeps/helicopter.death.plist",
    atlas118: "images/creeps/helicopter2.left.plist",
    atlas119: "images/creeps/helicopter2.down.plist",
    atlas121: "images/creeps/helicopter2.up.plist",
    atlas123: "images/creeps/helicopter2.left.plist",
    atlas124: "images/creeps/helicopter2.down.plist",
    atlas125: "images/creeps/helicopter2.up.plist",
    atlas126: "images/creeps/ship.left.plist",
    atlas127: "images/creeps/rembot.healing.plist",
    atlas128: "images/creeps/rembot.run.plist",
    atlas129: "images/creeps/cyberman1.plist",
	atlas130: "images/creeps/cyberman2.plist",
    atlas131: "images/creeps/flamethrower.plist",
    atlas132: "images/creeps/tank_m.plist",
    atlas133: "images/creeps/bigman.plist",
    atlas134: "images/creeps/helocopter_medic.plist",
    atlas135: "images/creeps/moto.plist",
    atlas137: "images/creeps/dron.plist",
    atlas138: "images/creeps/meh1.plist",
    atlas139: "images/creeps/meh2.plist",
	atlas140: "images/creeps/meh3.plist",
    atlas141: "images/creeps/bmp.plist",
    //atlas142: "",
    //atlas143: "",
    //atlas144: "",
    //atlas145: "",
    //atlas146: "",
    //atlas147: "",
    //atlas148: "",
    //atlas149: "",
	//atlas150: "",
    //atlas151: "",
    //atlas152: "",
    //atlas153: "",
    //atlas154: "",
    //atlas155: "",
    //atlas156: "",
    //atlas157: "",
    //atlas158: "",
    //atlas159: "",
	//atlas160: "",
    //atlas161: "",
    //atlas162: "",
    //atlas163: "",
    //atlas164: "",
    //atlas165: "",
    //atlas166: "",
    //atlas167: "",
    //atlas168: "",
    //atlas169: "",
	//atlas170: "",
    //atlas171: "",
    //atlas172: "",
    //atlas173: "",
    //atlas174: "",
    //atlas175: "",
    //atlas176: "",
    //atlas177: "",
    //atlas178: "",
    //atlas179: "",
	//atlas180: "",
    //atlas181: "",
    //atlas182: "",
    //atlas183: "",
    //atlas184: "",
    //atlas185: "",
    //atlas186: "",
    //atlas187: "",
    //atlas188: "",
    //atlas189: "",

};

var g_resources = [];
for (var i in res) {
    var resRoot = "res/_origin/";
    g_resources.push( resRoot + res[i]);
}
